version: 2
jobs:
  build:
    branches:
      ignore: gh-pages
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
              pip install --user -r requirements.txt
              sudo pip install pytest
              sudo pip install pycodestyle
              sudo pip install mypy
      - run:
          name: Run Tests
          command: |
            pytest -vv -p no:cacheprovider
      - run:
          name: Run Linter
          command: |
            pycodestyle --config=.config/pycodestyle.ini src/*
      # - run:
      #     name: Run MyPy Linter
      #     command: |
      #       mypy --config-file .config/mypy.ini src/*